/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.*;
import java.util.ArrayList;

/**
 *
 * @author mbp5503
 */
public class UpdateStock extends javax.swing.JPanel {

    private Mockup myGUI;
    private DB_Manager db = new DB_Manager();
    private ArrayList<? extends Item> itemList;

    /**
     * Creates new form UpdateStock1
     */
    public UpdateStock() {
        initComponents();
    }

    public UpdateStock(Mockup m) {
        myGUI = m;
        initComponents();
        ComponentCmb.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ComponentCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        StockTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComponentList = new javax.swing.JList<>();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Component Type");

        ComponentCmb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ComponentCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU", "MOBO", "RAM", "GPU", "PSU", "Case" }));
        ComponentCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComponentCmbItemStateChanged(evt);
            }
        });
        ComponentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentCmbActionPerformed(evt);
            }
        });
        ComponentCmb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ComponentCmbPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Enter Stock:");

        StockTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Stock");

        UpdateBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        UpdateBtn.setText("Update Stock");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        CancelBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Components: ");

        ComponentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComponentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ComponentList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComponentCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(StockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComponentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(StockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComponentCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComponentCmbItemStateChanged

    }//GEN-LAST:event_ComponentCmbItemStateChanged

    private void ComponentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentCmbActionPerformed
        // TODO add your handling code here:
        switch (ComponentCmb.getSelectedIndex()) {
            case 0: // displays CPU
                itemList = db.queryCPU();

                // add names from cpuList to cpuArray for the JList
                String[] cpuArray = new String[itemList.size()];
                for (int i = 0; i < cpuArray.length; i++) {
                    cpuArray[i] = itemList.get(i).getName();
                }

                // wipe and populate JList
                ComponentList.clearSelection();
                ComponentList.setListData(cpuArray);

                break;

            case 1: // displays MOBO
                itemList = db.queryMOBO();

                // add names from moboList to moboArray for the JList
                String[] moboArray = new String[itemList.size()];
                for (int i = 0; i < moboArray.length; i++) {
                    moboArray[i] = itemList.get(i).getName();
                }

                // wipes and updates JList
                ComponentList.clearSelection();
                ComponentList.setListData(moboArray);

                break;

            case 2: // displays RAM
                itemList = db.queryRAM();

                // add names from ramList to ramArray for the JList
                String[] ramArray = new String[itemList.size()];
                for (int i = 0; i < ramArray.length; i++) {
                    ramArray[i] = itemList.get(i).getName();
                }

                // wipes and updates JList
                ComponentList.clearSelection();
                ComponentList.setListData(ramArray);
                // query database

                break;

            case 3: // displays GPU
                itemList = db.queryGPU();

                // add names from gpuList to gpuArray for the JList
                String[] gpuArray = new String[itemList.size()];
                for (int i = 0; i < gpuArray.length; i++) {
                    gpuArray[i] = itemList.get(i).getName();
                }

                // wipes and updates JList
                ComponentList.clearSelection();
                ComponentList.setListData(gpuArray);

                break;

            case 4: // displays PSU

                itemList = db.queryPSU();

                // add names from psuList to psuArray for the JList
                String[] psuArray = new String[itemList.size()];
                for (int i = 0; i < psuArray.length; i++) {
                    psuArray[i] = itemList.get(i).getName();
                }

                // wipes and updates JList
                ComponentList.clearSelection();
                ComponentList.setListData(psuArray);

                break;

            case 5: // displays Case
                itemList = db.queryCase();

                // add names from caseList to csaeArray for the JList
                String[] caseArray = new String[itemList.size()];
                for (int i = 0; i < caseArray.length; i++) {
                    caseArray[i] = itemList.get(i).getName();
                }

                // wipes and updates JList
                ComponentList.clearSelection();
                ComponentList.setListData(caseArray);

                break;
        } // end of switch

    }//GEN-LAST:event_ComponentCmbActionPerformed

    private void ComponentCmbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ComponentCmbPropertyChange

    }//GEN-LAST:event_ComponentCmbPropertyChange

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        String item_name = ComponentList.getSelectedValue();
        int item_stock = Integer.parseInt(StockTxt.getText());
        switch (ComponentCmb.getSelectedIndex()) {
            case 0: // displays CPU

                db.updateCPUStock(item_name, item_stock);

                break;

            case 1: // displays MOBO

                db.updateMOBOStock(item_name, item_stock);
                break;

            case 2: // displays RAM

                // query database
                db.updateRAMStock(item_name, item_stock);

                break;

            case 3: // displays GPU

                db.updateGPUStock(item_name, item_stock);

                break;

            case 4: // displays PSU
                db.updatePSUStock(item_name, item_stock);

                break;

            case 5: // displays Case

                db.updateCaseStock(item_name, item_stock);

                break;
        } // end of switch

    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        myGUI.changePanel("update", "manager");
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void ComponentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComponentListMouseClicked

    }//GEN-LAST:event_ComponentListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> ComponentCmb;
    private javax.swing.JList<String> ComponentList;
    private javax.swing.JTextField StockTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
